# Generated by Django 6.0.4 on 2026-04-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Nombre')),
                ('descriptioin', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Foto')),
            ],
        ),
    ]
