# Generated by Django 6.0.4 on 2026-04-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
