# Generated by Django 6.0.4 on 2026-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_descriptioin_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto'),
        ),
    ]
